{{- $privateKey := default (genPrivateKey "ecdsa") .Values.app.jwt.privateKey | b64enc | quote }}

{{- if not .Values.app.jwt.privateKey }}
{{- $existingKey := (lookup "v1" "Secret" .Release.Namespace .Values.app.jwt.secretName) }}
{{- if $existingKey }}
{{- $privateKey = index $existingKey.data "key" }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.jwt.secretName }}"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  key: {{ $privateKey }}
